spring:
  datasource:
    url: jdbc:mysql://3.1.138.158:3666/shal?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: redis
    port: 6379

line.bot:
  channel-token: 'mamocK9697OSCly7r24ylt6exny6VRN1W0TMFvkhMZubYUvh820rcXRjOPnOjK2O2lmk8nuB6ZFgdW73N71SJ88IfCuDJLTkVXe4fmbxkwu2oRqm8E2skNH6mV4NjAdvdgyYuSEsiu0AAUDXCOGIYgdB04t89/1O/w1cDnyilFU='
  channel-secret: 'd33b95ab4b2aff4df0d3343b0b75b31c'
  handler.path: /callback
server:
  port: ${PORT:5000}