spring:
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://localhost:3306/shal?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    host: localhost
    port: 6379
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

graphql:
  servlet:
    # Sets if GraphQL servlet should be created and exposed. If not specified defaults to "true".
    enabled: true
    # Sets the path where GraphQL servlet will be exposed. If not specified defaults to "/graphql"
    mapping: /graphql
    corsEnabled: false
shal:
  postcodeDb: postcodeDb/postcodedb.json

line.bot:
  channel-token: 'IcGn7acwCB/Bg62RBasZ7CJre+qLkRlUza3lANfUWThjpQIdeABh7mBkSeGoDWxQPYGK03Xh1aLZTg4zWOyNUektMLF1qm7MQV2eJbUbCs0RrP6WIJqPyvqw/NtouQ7iGMyJ2L8iMgKRElF8hB4V2QdB04t89/1O/w1cDnyilFU='
  channel-secret: '465b7dd6d7fb2c69a29dcdc8f553c88b'
  handler.path: /callback