version: "3.7"
services:
  maincontroller:
    image: shal/dev
    ports:
      - 9988:8080
    environment:
      - JAVA_PROFILE=dev-release,db
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  redis_data: